#!/usr/bin/tclsh
if {$argc == 0} {
    puts "Usage: $argv0 <day> \[part\]"
    exit
}
source readlines.tcl
set part2 [expr {$argc >= 2 && [lindex $argv 1] != 1}]
source [format "adv%02d.tcl" [lindex $argv 0]]
